name: (action) build, export and deploy next.js to github page

jobs:
  build:
    name: Build, export and deploy next.js to github page
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      steps:
        - name: Build project
          run: npm run build
        - name: Export static files
          run: npm run export
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.3.3
          with:
            branch: main
            folder: out