import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import { ReactElement } from 'react';

export default function Landing () {

    const router = useRouter();

    const handleClick = () => {
        router.push(`/specs/swagger`, undefined, {
            shallow: true,
        });
    };

    return (
        <>
            <Head>
                <title>App Landing</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="/favicon.ico"
                />
            </Head>
            <Box
                component="header"
                padding={2}
                position="absolute"
                width="100%"
            >
                <Container maxWidth="lg">
                    <Box
                        display="flex"
                        justifyContent="space-between"
                        alignItems="center"
                    >
                        <Image
                            src="https://kidsloop.net/wp-content/uploads/2021/08/kidsloop.svg"
                            alt="Vercel Logo"
                            width={200}
                            height={100}
                        />
                    </Box>
                </Container>
            </Box>
            <Box
                paddingY={20}
                sx={{
                    backgroundColor: `primary.dark`,
                }}
            >
                <Container>
                    <Box display="flex">
                        <Box width="50%">
                            <Typography
                                variant="h2"
                                color="white"
                            >
                        Education infrastructure for the internet
                            </Typography>
                            <Typography color="white">Millions of businesses of all sizes—from startups to large enterprises—use Stripe’s software and APIs to accept payments, send payouts, and manage their businesses online.</Typography>
                            <Box
                                paddingTop={3}
                            >
                                <Button
                                    variant="contained"
                                    color="primary"
                                    onClick={handleClick}
                                >
                                    Learn More
                                </Button>
                            </Box>
                        </Box>
                    </Box>
                </Container>
            </Box>
            <main>
                <Box
                    component="section"
                    p={8}
                    bgcolor="white"
                >
                    <Container>
                        <Box>
                            <Box width="40%">
                                <Typography
                                    variant="h4"
                                    paddingBottom={2}
                                >
                            A fully integrated suite of payments products
                                </Typography>
                            </Box>
                            <Box
                                display="flex"
                                width="100%"
                            >
                                <Box paddingRight={4}>
                                    <Typography>
                                We bring together everything that’s required to
                                build websites and apps that accept payments and
                                send payouts globally. Stripe’s products power
                                payments for online and in-person retailers,
                                subscriptions businesses, software platforms and
                                marketplaces, and everything in between.
                                    </Typography>
                                </Box>
                                <Box>
                                    <Typography>
                                We also help companies beat fraud, send
                                invoices, issue virtual and physical cards, get
                                financing, manage business spend, and much more.
                                    </Typography>
                                </Box>
                            </Box>
                        </Box>
                    </Container>

                </Box>
            </main>
            <Box
                component="footer"
                p={8}
                bgcolor="whitesmoke"
            >
                <Container>
                    <a
                        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                Powered by{` `}
                        <span>
                            <Image
                                src="/vercel.svg"
                                alt="Vercel Logo"
                                width={72}
                                height={16}
                            />
                        </span>
                    </a>
                </Container>
            </Box>
        </>
    );
}

Landing.getLayout = (page: ReactElement) => {
    return <>{page}</>;
};
