name: Deploy to github pages

on:
  workflow_dispatch: # enables on-demand/manual triggering
  
  # enable this for on push automatically run workflow
  # push:
  #   branches:
  #   - main

jobs:
  install:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # We will deploy with only one version of node  

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/

      # - name: Find node_modules cache
      #   id: cache-node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ./node_modules
      #     key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        # if: steps.cache-node_modules.outputs.cache-hit != 'true'
        shell: bash
        run: | 
          npm ci
          npm run build --if-present
          npm run export
        env:
          NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}

      # - name: npm ci, build, export
      #   run: |
      #     npm ci
      #     npm run build --if-present
      #     npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: main
          folder: ./out
