name: Deploy to github pages

on:
  workflow_dispatch: # enables on-demand/manual triggering
  
  # enable this for on push automatically run workflow
  # push:
  #   branches:
  #   - main

jobs:
    install:
        uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v3.2.1
        secrets:
            NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
    build:
      needs: [install]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Gh pages deploy
          id: deploy
          uses: ./.github/actions/deploy