name: Deploy to github pages

on:
  workflow_dispatch: # enables on-demand/manual triggering
  
  # enable this for on push automatically run workflow
  # push:
  #   branches:
  #   - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: KL-Engineering/github-action-workflows/.github/workflows/npm-ci.yml@v3.2.1
        secrets:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - name: Build project
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: main
          folder: ./out
